training_pipeline_config:
  pipeline_name: Insurance
  artifact_dir: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_data_path: E:/Documents/d_s/full_stack/ML_project/Data
  source_file: insurance.csv
  raw_dir: raw_data
  ingested_train_dir: train
  ingested_test_dir: test

data_validation:
  root_dir: artifacts/data_validation
  report_file_name: report.json
  report_page_file_name: report.html


data_transformation_config:
  root_dir: artifacts/data_transformation
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl

model_trainer_config:
  root_dir: artifacts/model_trainer
  trained_model_dir: trained_model
  model_file_name: model.pkl
  base_accuracy: 0.6
  model_config_dir: config
  model_config_file_name: model.yaml


model_evaluation_config:
  root_dir: artifacts/model_evaluation
  model_evaluation_file_name: model_evaluation.yaml
  

model_pusher_config:
  model_export_dir: saved_models